// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: owners.sql

package sqlcgen

import (
	"context"
)

const getOwnerByID = `-- name: GetOwnerByID :one
SELECT id, name, access_token, chair_register_token, created_at, updated_at FROM owners WHERE id = ? LIMIT 1
`

func (q *Queries) GetOwnerByID(ctx context.Context, id string) (Owner, error) {
	row := q.db.QueryRow(ctx, getOwnerByID, id)
	var i Owner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AccessToken,
		&i.ChairRegisterToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
