# グループ化のルールを記述
aggregates:
  - pattern: ^/api/app/rides/[a-zA-Z0-9_-]+/evaluation
    name: /api/app/rides/*/evaluation
  - pattern: ^/api/chair/rides/[a-zA-Z0-9_-]+/status
    name: /api/chair/rides/*/status

  # 静的アセットのグループ化
  - pattern: ^/assets/.+
    name: /assets/*
  - pattern: ^/images/.+
    name: /images/*
# ソート順
# sort: count
